const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { loadContent, buildContent } = require('../scripts/content.cjs')

function fixture(t) {
    const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'homepage-markdown-'))
    t.after(() => fs.rmSync(folder, { recursive: true, force: true }))
    const root = path.join(folder, 'content')
    const output = path.join(folder, 'dist')
    fs.mkdirSync(root)
    const write = (name, body) => {
        const file = path.join(root, name)
        fs.mkdirSync(path.dirname(file), { recursive: true })
        fs.writeFileSync(file, body)
    }
    write('channels.json', JSON.stringify({ blog: { title: 'Blog', description: '文章' }, about: { title: 'About', description: '简介' } }))
    const build = () => buildContent({ contentRoot: root, outputRoot: output, templateRoot: path.join(__dirname, '../src'), templateData: { main: { name: 'lircOS' }, assetVersion: 'test' } })
    return { root, output, write, build }
}

test('renders Markdown and rewrites nested note, heading and attachment links', t => {
    const f = fixture(t)
    f.write('about/关于我.md', '---\npublish: true\n---\n## 我的研究\n\n简介')
    f.write('assets/photo.png', Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lXcAAAAASUVORK5CYII=', 'base64'))
    f.write('blog/nested/文章.md', '---\ntitle: 测试文章\ndate: 2026-10-02\npublish: true\n---\n## 小标题\n\n**粗体**与[关于我](../../about/关于我.md#我的研究)\n\n![图片](../../assets/photo.png)\n\n```js\nconst text = "[[不是链接]]"\n```\n\n| A | B |\n| --- | --- |\n| 1 | 2 |')
    const result = f.build()
    const note = result.notes.get('blog/nested/文章.md')
    assert.match(note.html, /<strong>粗体<\/strong>/)
    assert.match(note.html, /<h2 id="小标题">/)
    assert.match(note.html, /href="\.\.\/\.\.\/\.\.\/about\/posts\/%E5%85%B3%E4%BA%8E%E6%88%91.html#%E6%88%91%E7%9A%84%E7%A0%94%E7%A9%B6"/)
    assert.match(note.html, /src="\.\.\/\.\.\/\.\.\/content-assets\/assets\/photo.png"/)
    assert.match(note.html, /<table>/)
    assert.match(note.html, /\[\[不是链接\]\]/)
    const html = fs.readFileSync(path.join(f.output, note.output), 'utf8')
    assert.match(html, /href="\.\.\/\.\.\/\.\.\/css\/channels.css/)
    assert.ok(fs.existsSync(path.join(f.output, 'content-assets/assets/photo.png')))
    assert.match(fs.readFileSync(path.join(f.output, 'blog/index.html'), 'utf8'), /posts\/nested\/%E6%96%87%E7%AB%A0.html/)
})

test('publishes only opted-in notes and referenced attachments; removes stale pages', t => {
    const f = fixture(t)
    f.write('blog/公开.md', '---\npublish: true\n---\n公开正文')
    f.write('blog/草稿.md', '---\npublish: false\n---\nPRIVATE_DRAFT')
    f.write('blog/未标记.md', 'UNMARKED_NOTE')
    f.write('assets/unused.txt', 'PRIVATE_ATTACHMENT')
    f.write('.obsidian/workspace.json', 'PRIVATE_SETTINGS')
    f.write('_templates/模板.md', '---\npublish: true\n---\nTEMPLATE')
    const first = f.build()
    assert.equal(first.notes.size, 1)
    assert.equal(first.attachments.size, 0)
    assert.equal(fs.existsSync(path.join(f.output, '.obsidian')), false)
    f.write('blog/公开.md', '---\npublish: false\n---\n公开正文')
    const second = f.build()
    assert.equal(second.notes.size, 0)
    assert.equal(fs.existsSync(path.join(f.output, 'blog/posts/公开.html')), false)
    assert.match(fs.readFileSync(path.join(f.output, 'blog/index.html'), 'utf8'), /待更新/)
})

test('refuses links to unpublished notes and reports the source file', t => {
    const f = fixture(t)
    f.write('blog/公开.md', '---\npublish: true\n---\n[草稿](草稿.md)')
    f.write('blog/草稿.md', '---\npublish: false\n---\nPRIVATE')
    assert.throws(() => loadContent(f.root), /blog\/公开.md.*没有发布/)
})

test('refuses escaping and symlinked attachments', t => {
    const f = fixture(t)
    f.write('blog/公开.md', '---\npublish: true\n---\n[外部文件](../../outside.txt)')
    assert.throws(() => loadContent(f.root), /超出公开内容目录/)
    f.write('.obsidian/private.txt', 'PRIVATE')
    fs.mkdirSync(path.join(f.root, 'assets'))
    fs.symlinkSync(path.join(f.root, '.obsidian/private.txt'), path.join(f.root, 'assets/leak.txt'))
    f.write('blog/公开.md', '---\npublish: true\n---\n[附件](../assets/leak.txt)')
    assert.throws(() => loadContent(f.root), /附件不能链接/)
})

test('supports Obsidian YAML dates, ordering, drafts and safe HTML rendering', t => {
    const f = fixture(t)
    f.write('blog/older.md', '---\npublish: true\ndate: 2023-11-01\norder: 1\n---\n<script>alert(1)</script>')
    f.write('blog/newer.md', '---\npublish: true\ndate: 2026-10-02\n---\n新文章')
    f.write('blog/draft.md', '---\npublish: false\ndate: "{{date}}"\n---\n草稿')
    const content = loadContent(f.root)
    assert.equal(content.channels.blog.items[0].file, 'blog/older.md')
    assert.equal(content.channels.blog.items[1].date, '2026-10-02')
    assert.match(content.notes.get('blog/older.md').html, /&lt;script&gt;/)
    f.write('blog/invalid.md', '---\npublish: "false"\n---\n不合法')
    assert.throws(() => loadContent(f.root), /publish 必须/)
})
